source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }
gem 'dotenv-rails', git: "https://github.com/bkeepers/dotenv", branch: "master"

ruby '3.0.2'

gem 'rails', '~> 6.1.6', '>= 6.1.6.1'
gem 'mysql2', '~> 0.5'
gem 'puma', '~> 5.0'
gem 'jbuilder', '~> 2.7'
gem 'bootsnap', '>= 1.4.4', require: false

gem 'rack-cors'


group :development, :test do
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
  gem 'better_errors'
end

group :development do
  gem 'listen', '~> 3.3'
  gem 'spring'
end

group :test do
    gem 'rspec-rails', '~> 4.0'
    gem 'factory_bot_rails'
    gem 'faker'
    gem 'guard-rspec'
    gem 'database_cleaner'
    gem 'rspec-repeat'
    gem 'shoulda-matchers', '~> 5.0'
    gem 'simplecov'
end

gem 'faraday'
gem 'oj'

gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]


gem 'searchkick'
gem 'elasticsearch'

gem 'dalli'