name: App Tests

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'src/frontend/src/**'
      - 'src/backend/app/**'

jobs:
  Tests:
    timeout-minutes: 5
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Run tests container
      env:
        PASSWORD: ${{ secrets.PASSWORD }}
      run: |
        docker-compose up -d mariadb redis elasticsearch
        sleep 5
        docker-compose run tests

